### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by chantake1128** [chantake1128/furima-41428#20]
# What
フリマアプリの挙動確認をお願いします。
# Why
最終課題の確認のため
# URL
https://furima-41428.onrender.com

**Comment by ghost** [comment]
@chantake1128 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
項目の「ゲーム」が重複しております。
実装条件シートの条件にそって修正をお願いいたします。
<img width="383" alt="スクリーンショット 2024-08-26 9 12 11" src="https://github.com/user-attachments/assets/e5e1dc11-d478-4516-ac40-2df8896d97a3">

- [x] **発送までの日数は、「---、1~2日で発送、2~3日で発送、4~7日で発送」の4項目が表示されること（--- は初期値として設定すること）**
「4-7日」となっております。この表記の修正を願いいたします。
<img width="422" alt="スクリーンショット 2024-08-26 9 16 12" src="https://github.com/user-attachments/assets/761557aa-46d8-47a7-be57-6bf789734a24">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by chantake1128** [comment]
ありがとうございます。
修正しました

**Comment by ghost** [comment]
@chantake1128 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
ご案内いただいたURLをクリックしましたところ、502のエラーが出ました。
今一度本番環境でアプリが開くかをご確認いただきご提出をお願いいたします。
<img width="677" alt="スクリーンショット 2024-08-26 10 50 26" src="https://github.com/user-attachments/assets/a921f161-eebf-4687-8318-2faccccadf79">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by chantake1128** [comment]
再度確認しましたが問題なく開けております

**Comment by motomuun** [comment]
@chantake1128 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
502のエラーは一時的なエラーであった可能性が高いです。大変失礼致しました。

達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
